version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/components/heimdall/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/experimental/java/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/experimental/spring/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
