approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
]

ignored = [
  "github.com/davecgh/go-spew", # ISC license
  "github.com/gogo/protobuf",
  "google.golang.org/protobuf",
  "github.com/ghodss/yaml",
  "sigs.k8s.io/yaml", # Forked from above
  "gopkg.in/fsnotify.v1",
  "gopkg.in/square/go-jose.v2", # Apache v2.0
  "github.com/cisco-open/libnasp", # Apache v2.0
  "emperror.dev/errors", # MIT license
  "golang.ngrok.com/muxado" # MIT license
]

[header]
ignoreFiles = [
  "*.pb.go",
  "istio_ca_client.go",
]

ignorePaths = [
  "playground",
]

template = """Copyright (c) :YEAR: Cisco and/or its affiliates. All rights reserved.
"""
