// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package response

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/messages/describelogdirs/response/describelogdirsresult"
	typesbytes "github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var describeLogDirsResultErrorCode = fields.Context{
	SpecName:                    "ErrorCode",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var describeLogDirsResultLogDir = fields.Context{
	SpecName:                    "LogDir",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var describeLogDirsResultTopics = fields.Context{
	SpecName:                    "Topics",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var describeLogDirsResultTotalBytes = fields.Context{
	SpecName:                    "TotalBytes",
	CustomDefaultValue:          int64(-1),
	LowestSupportedVersion:      4,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var describeLogDirsResultUsableBytes = fields.Context{
	SpecName:                    "UsableBytes",
	CustomDefaultValue:          int64(-1),
	LowestSupportedVersion:      4,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}

type DescribeLogDirsResult struct {
	topics              []describelogdirsresult.DescribeLogDirsTopic
	unknownTaggedFields []fields.RawTaggedField
	logDir              fields.NullableString
	totalBytes          int64
	usableBytes         int64
	errorCode           int16
	isNil               bool
}

func (o *DescribeLogDirsResult) ErrorCode() int16 {
	return o.errorCode
}

func (o *DescribeLogDirsResult) SetErrorCode(val int16) {
	o.isNil = false
	o.errorCode = val
}

func (o *DescribeLogDirsResult) LogDir() fields.NullableString {
	return o.logDir
}

func (o *DescribeLogDirsResult) SetLogDir(val fields.NullableString) {
	o.isNil = false
	o.logDir = val
}

func (o *DescribeLogDirsResult) Topics() []describelogdirsresult.DescribeLogDirsTopic {
	return o.topics
}

func (o *DescribeLogDirsResult) SetTopics(val []describelogdirsresult.DescribeLogDirsTopic) {
	o.isNil = false
	o.topics = val
}

func (o *DescribeLogDirsResult) TotalBytes() int64 {
	return o.totalBytes
}

func (o *DescribeLogDirsResult) SetTotalBytes(val int64) {
	o.isNil = false
	o.totalBytes = val
}

func (o *DescribeLogDirsResult) UsableBytes() int64 {
	return o.usableBytes
}

func (o *DescribeLogDirsResult) SetUsableBytes(val int64) {
	o.isNil = false
	o.usableBytes = val
}

func (o *DescribeLogDirsResult) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *DescribeLogDirsResult) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *DescribeLogDirsResult) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	errorCodeField := fields.Int16{Context: describeLogDirsResultErrorCode}
	if err := errorCodeField.Read(buf, version, &o.errorCode); err != nil {
		return errors.WrapIf(err, "couldn't set \"errorCode\" field")
	}

	logDirField := fields.String{Context: describeLogDirsResultLogDir}
	if err := logDirField.Read(buf, version, &o.logDir); err != nil {
		return errors.WrapIf(err, "couldn't set \"logDir\" field")
	}

	topicsField := fields.ArrayOfStruct[describelogdirsresult.DescribeLogDirsTopic, *describelogdirsresult.DescribeLogDirsTopic]{Context: describeLogDirsResultTopics}
	topics, err := topicsField.Read(buf, version)
	if err != nil {
		return errors.WrapIf(err, "couldn't set \"topics\" field")
	}
	o.topics = topics

	totalBytesField := fields.Int64{Context: describeLogDirsResultTotalBytes}
	if err := totalBytesField.Read(buf, version, &o.totalBytes); err != nil {
		return errors.WrapIf(err, "couldn't set \"totalBytes\" field")
	}

	usableBytesField := fields.Int64{Context: describeLogDirsResultUsableBytes}
	if err := usableBytesField.Read(buf, version, &o.usableBytes); err != nil {
		return errors.WrapIf(err, "couldn't set \"usableBytes\" field")
	}

	// process tagged fields

	if version < DescribeLogDirsResultLowestSupportedFlexVersion() || version > DescribeLogDirsResultHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *DescribeLogDirsResult) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	errorCodeField := fields.Int16{Context: describeLogDirsResultErrorCode}
	if err := errorCodeField.Write(buf, version, o.errorCode); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"errorCode\" field")
	}
	logDirField := fields.String{Context: describeLogDirsResultLogDir}
	if err := logDirField.Write(buf, version, o.logDir); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"logDir\" field")
	}

	topicsField := fields.ArrayOfStruct[describelogdirsresult.DescribeLogDirsTopic, *describelogdirsresult.DescribeLogDirsTopic]{Context: describeLogDirsResultTopics}
	if err := topicsField.Write(buf, version, o.topics); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"topics\" field")
	}

	totalBytesField := fields.Int64{Context: describeLogDirsResultTotalBytes}
	if err := totalBytesField.Write(buf, version, o.totalBytes); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"totalBytes\" field")
	}
	usableBytesField := fields.Int64{Context: describeLogDirsResultUsableBytes}
	if err := usableBytesField.Write(buf, version, o.usableBytes); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"usableBytes\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < DescribeLogDirsResultLowestSupportedFlexVersion() || version > DescribeLogDirsResultHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *DescribeLogDirsResult) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *DescribeLogDirsResult) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 6)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.errorCode); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"errorCode\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.logDir); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"logDir\""), b}, []byte(": ")))
	}
	if b, err := fields.ArrayOfStructMarshalJSON("topics", o.topics); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.totalBytes); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"totalBytes\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.usableBytes); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"usableBytes\""), b}, []byte(": ")))
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *DescribeLogDirsResult) IsNil() bool {
	return o.isNil
}

func (o *DescribeLogDirsResult) Clear() {
	o.Release()
	o.isNil = true

	o.topics = nil
	o.unknownTaggedFields = nil
}

func (o *DescribeLogDirsResult) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.errorCode = 0
	o.logDir.SetValue("")
	for i := range o.topics {
		o.topics[i].Release()
	}
	o.topics = nil
	o.totalBytes = -1
	o.usableBytes = -1

	o.isNil = false
}

func (o *DescribeLogDirsResult) Equal(that *DescribeLogDirsResult) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if o.errorCode != that.errorCode {
		return false
	}
	if !o.logDir.Equal(&that.logDir) {
		return false
	}
	if len(o.topics) != len(that.topics) {
		return false
	}
	for i := range o.topics {
		if !o.topics[i].Equal(&that.topics[i]) {
			return false
		}
	}
	if o.totalBytes != that.totalBytes {
		return false
	}
	if o.usableBytes != that.usableBytes {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *DescribeLogDirsResult) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	errorCodeField := fields.Int16{Context: describeLogDirsResultErrorCode}
	fieldSize, err = errorCodeField.SizeInBytes(version, o.errorCode)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"errorCode\" field")
	}
	size += fieldSize

	logDirField := fields.String{Context: describeLogDirsResultLogDir}
	fieldSize, err = logDirField.SizeInBytes(version, o.logDir)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"logDir\" field")
	}
	size += fieldSize

	topicsField := fields.ArrayOfStruct[describelogdirsresult.DescribeLogDirsTopic, *describelogdirsresult.DescribeLogDirsTopic]{Context: describeLogDirsResultTopics}
	fieldSize, err = topicsField.SizeInBytes(version, o.topics)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"topics\" field")
	}
	size += fieldSize

	totalBytesField := fields.Int64{Context: describeLogDirsResultTotalBytes}
	fieldSize, err = totalBytesField.SizeInBytes(version, o.totalBytes)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"totalBytes\" field")
	}
	size += fieldSize

	usableBytesField := fields.Int64{Context: describeLogDirsResultUsableBytes}
	fieldSize, err = usableBytesField.SizeInBytes(version, o.usableBytes)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"usableBytes\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < DescribeLogDirsResultLowestSupportedFlexVersion() || version > DescribeLogDirsResultHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *DescribeLogDirsResult) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.logDir.Release()
	for i := range o.topics {
		o.topics[i].Release()
	}
	o.topics = nil
}

func (o *DescribeLogDirsResult) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *DescribeLogDirsResult) validateNonIgnorableFields(version int16) error {
	return nil
}

func DescribeLogDirsResultLowestSupportedVersion() int16 {
	return 0
}

func DescribeLogDirsResultHighestSupportedVersion() int16 {
	return 32767
}

func DescribeLogDirsResultLowestSupportedFlexVersion() int16 {
	return 2
}

func DescribeLogDirsResultHighestSupportedFlexVersion() int16 {
	return 32767
}

func DescribeLogDirsResultDefault() DescribeLogDirsResult {
	var d DescribeLogDirsResult
	d.SetDefault()

	return d
}
