// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package offsetfetchresponsetopics

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	typesbytes "github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var offsetFetchResponsePartitionsPartitionIndex = fields.Context{
	SpecName:                    "PartitionIndex",
	LowestSupportedVersion:      8,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  6,
	HighestSupportedFlexVersion: 32767,
}
var offsetFetchResponsePartitionsCommittedOffset = fields.Context{
	SpecName:                    "CommittedOffset",
	LowestSupportedVersion:      8,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  6,
	HighestSupportedFlexVersion: 32767,
}
var offsetFetchResponsePartitionsCommittedLeaderEpoch = fields.Context{
	SpecName:                    "CommittedLeaderEpoch",
	CustomDefaultValue:          int32(-1),
	LowestSupportedVersion:      8,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  6,
	HighestSupportedFlexVersion: 32767,
}
var offsetFetchResponsePartitionsMetadata = fields.Context{
	SpecName:                        "Metadata",
	LowestSupportedVersion:          8,
	HighestSupportedVersion:         32767,
	LowestSupportedFlexVersion:      6,
	HighestSupportedFlexVersion:     32767,
	LowestSupportedNullableVersion:  8,
	HighestSupportedNullableVersion: 32767,
}
var offsetFetchResponsePartitionsErrorCode = fields.Context{
	SpecName:                    "ErrorCode",
	LowestSupportedVersion:      8,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  6,
	HighestSupportedFlexVersion: 32767,
}

type OffsetFetchResponsePartitions struct {
	unknownTaggedFields  []fields.RawTaggedField
	metadata             fields.NullableString
	committedOffset      int64
	partitionIndex       int32
	committedLeaderEpoch int32
	errorCode            int16
	isNil                bool
}

func (o *OffsetFetchResponsePartitions) PartitionIndex() int32 {
	return o.partitionIndex
}

func (o *OffsetFetchResponsePartitions) SetPartitionIndex(val int32) {
	o.isNil = false
	o.partitionIndex = val
}

func (o *OffsetFetchResponsePartitions) CommittedOffset() int64 {
	return o.committedOffset
}

func (o *OffsetFetchResponsePartitions) SetCommittedOffset(val int64) {
	o.isNil = false
	o.committedOffset = val
}

func (o *OffsetFetchResponsePartitions) CommittedLeaderEpoch() int32 {
	return o.committedLeaderEpoch
}

func (o *OffsetFetchResponsePartitions) SetCommittedLeaderEpoch(val int32) {
	o.isNil = false
	o.committedLeaderEpoch = val
}

func (o *OffsetFetchResponsePartitions) Metadata() fields.NullableString {
	return o.metadata
}

func (o *OffsetFetchResponsePartitions) SetMetadata(val fields.NullableString) {
	o.isNil = false
	o.metadata = val
}

func (o *OffsetFetchResponsePartitions) ErrorCode() int16 {
	return o.errorCode
}

func (o *OffsetFetchResponsePartitions) SetErrorCode(val int16) {
	o.isNil = false
	o.errorCode = val
}

func (o *OffsetFetchResponsePartitions) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *OffsetFetchResponsePartitions) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *OffsetFetchResponsePartitions) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	partitionIndexField := fields.Int32{Context: offsetFetchResponsePartitionsPartitionIndex}
	if err := partitionIndexField.Read(buf, version, &o.partitionIndex); err != nil {
		return errors.WrapIf(err, "couldn't set \"partitionIndex\" field")
	}

	committedOffsetField := fields.Int64{Context: offsetFetchResponsePartitionsCommittedOffset}
	if err := committedOffsetField.Read(buf, version, &o.committedOffset); err != nil {
		return errors.WrapIf(err, "couldn't set \"committedOffset\" field")
	}

	committedLeaderEpochField := fields.Int32{Context: offsetFetchResponsePartitionsCommittedLeaderEpoch}
	if err := committedLeaderEpochField.Read(buf, version, &o.committedLeaderEpoch); err != nil {
		return errors.WrapIf(err, "couldn't set \"committedLeaderEpoch\" field")
	}

	metadataField := fields.String{Context: offsetFetchResponsePartitionsMetadata}
	if err := metadataField.Read(buf, version, &o.metadata); err != nil {
		return errors.WrapIf(err, "couldn't set \"metadata\" field")
	}

	errorCodeField := fields.Int16{Context: offsetFetchResponsePartitionsErrorCode}
	if err := errorCodeField.Read(buf, version, &o.errorCode); err != nil {
		return errors.WrapIf(err, "couldn't set \"errorCode\" field")
	}

	// process tagged fields

	if version < OffsetFetchResponsePartitionsLowestSupportedFlexVersion() || version > OffsetFetchResponsePartitionsHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *OffsetFetchResponsePartitions) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	partitionIndexField := fields.Int32{Context: offsetFetchResponsePartitionsPartitionIndex}
	if err := partitionIndexField.Write(buf, version, o.partitionIndex); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"partitionIndex\" field")
	}
	committedOffsetField := fields.Int64{Context: offsetFetchResponsePartitionsCommittedOffset}
	if err := committedOffsetField.Write(buf, version, o.committedOffset); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"committedOffset\" field")
	}
	committedLeaderEpochField := fields.Int32{Context: offsetFetchResponsePartitionsCommittedLeaderEpoch}
	if err := committedLeaderEpochField.Write(buf, version, o.committedLeaderEpoch); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"committedLeaderEpoch\" field")
	}
	metadataField := fields.String{Context: offsetFetchResponsePartitionsMetadata}
	if err := metadataField.Write(buf, version, o.metadata); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"metadata\" field")
	}
	errorCodeField := fields.Int16{Context: offsetFetchResponsePartitionsErrorCode}
	if err := errorCodeField.Write(buf, version, o.errorCode); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"errorCode\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < OffsetFetchResponsePartitionsLowestSupportedFlexVersion() || version > OffsetFetchResponsePartitionsHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *OffsetFetchResponsePartitions) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *OffsetFetchResponsePartitions) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 6)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.partitionIndex); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"partitionIndex\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.committedOffset); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"committedOffset\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.committedLeaderEpoch); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"committedLeaderEpoch\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.metadata); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"metadata\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.errorCode); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"errorCode\""), b}, []byte(": ")))
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *OffsetFetchResponsePartitions) IsNil() bool {
	return o.isNil
}

func (o *OffsetFetchResponsePartitions) Clear() {
	o.Release()
	o.isNil = true

	o.unknownTaggedFields = nil
}

func (o *OffsetFetchResponsePartitions) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.partitionIndex = 0
	o.committedOffset = 0
	o.committedLeaderEpoch = -1
	o.metadata.SetValue("")
	o.errorCode = 0

	o.isNil = false
}

func (o *OffsetFetchResponsePartitions) Equal(that *OffsetFetchResponsePartitions) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if o.partitionIndex != that.partitionIndex {
		return false
	}
	if o.committedOffset != that.committedOffset {
		return false
	}
	if o.committedLeaderEpoch != that.committedLeaderEpoch {
		return false
	}
	if !o.metadata.Equal(&that.metadata) {
		return false
	}
	if o.errorCode != that.errorCode {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *OffsetFetchResponsePartitions) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	partitionIndexField := fields.Int32{Context: offsetFetchResponsePartitionsPartitionIndex}
	fieldSize, err = partitionIndexField.SizeInBytes(version, o.partitionIndex)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"partitionIndex\" field")
	}
	size += fieldSize

	committedOffsetField := fields.Int64{Context: offsetFetchResponsePartitionsCommittedOffset}
	fieldSize, err = committedOffsetField.SizeInBytes(version, o.committedOffset)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"committedOffset\" field")
	}
	size += fieldSize

	committedLeaderEpochField := fields.Int32{Context: offsetFetchResponsePartitionsCommittedLeaderEpoch}
	fieldSize, err = committedLeaderEpochField.SizeInBytes(version, o.committedLeaderEpoch)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"committedLeaderEpoch\" field")
	}
	size += fieldSize

	metadataField := fields.String{Context: offsetFetchResponsePartitionsMetadata}
	fieldSize, err = metadataField.SizeInBytes(version, o.metadata)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"metadata\" field")
	}
	size += fieldSize

	errorCodeField := fields.Int16{Context: offsetFetchResponsePartitionsErrorCode}
	fieldSize, err = errorCodeField.SizeInBytes(version, o.errorCode)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"errorCode\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < OffsetFetchResponsePartitionsLowestSupportedFlexVersion() || version > OffsetFetchResponsePartitionsHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *OffsetFetchResponsePartitions) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.metadata.Release()
}

func (o *OffsetFetchResponsePartitions) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *OffsetFetchResponsePartitions) validateNonIgnorableFields(version int16) error {
	if !offsetFetchResponsePartitionsPartitionIndex.IsSupportedVersion(version) {
		if o.partitionIndex != 0 {
			return errors.New(strings.Join([]string{"attempted to write non-default \"partitionIndex\" at version", strconv.Itoa(int(version))}, " "))
		}
	}
	if !offsetFetchResponsePartitionsCommittedOffset.IsSupportedVersion(version) {
		if o.committedOffset != 0 {
			return errors.New(strings.Join([]string{"attempted to write non-default \"committedOffset\" at version", strconv.Itoa(int(version))}, " "))
		}
	}
	if !offsetFetchResponsePartitionsMetadata.IsSupportedVersion(version) {
		if o.metadata.Bytes() != nil {
			return errors.New(strings.Join([]string{"attempted to write non-default \"metadata\" at version", strconv.Itoa(int(version))}, " "))
		}
	}
	if !offsetFetchResponsePartitionsErrorCode.IsSupportedVersion(version) {
		if o.errorCode != 0 {
			return errors.New(strings.Join([]string{"attempted to write non-default \"errorCode\" at version", strconv.Itoa(int(version))}, " "))
		}
	}
	return nil
}

func OffsetFetchResponsePartitionsLowestSupportedVersion() int16 {
	return 8
}

func OffsetFetchResponsePartitionsHighestSupportedVersion() int16 {
	return 32767
}

func OffsetFetchResponsePartitionsLowestSupportedFlexVersion() int16 {
	return 6
}

func OffsetFetchResponsePartitionsHighestSupportedFlexVersion() int16 {
	return 32767
}

func OffsetFetchResponsePartitionsDefault() OffsetFetchResponsePartitions {
	var d OffsetFetchResponsePartitions
	d.SetDefault()

	return d
}
