apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nasp-webhook-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nasp-webhook-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "nasp-webhook-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        sidecar.istio.io/inject: "false"
      labels:
        {{- include "nasp-webhook-controller.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "nasp-webhook-controller.fullname" . }}
      containers:
        - name: manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /manager
          args:
            - "--webhook-name={{ include "nasp-webhook-controller.fullname" . }}"
            - "--webhook-port={{ .Values.webhook.port }}"
            - "--istio-ca-address={{ .Values.istio.caAddress | required ".Values.istio.caAddress is required." }}"
            - "--istio-version={{ .Values.istio.version | required ".Values.istio.version is required." }}"
            - "--istio-mesh-id={{ .Values.istio.meshID | required ".Values.istio.meshID is required." }}"
            - "--istio-network={{ .Values.istio.network | required ".Values.istio.network is required." }}"
            - "--istio-revision={{ .Values.istio.revision | required ".Values.istio.revision is required." }}"
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
            - name: healthz
              containerPort: {{ .Values.healthz.port }}
              protocol: TCP
            - containerPort: {{ .Values.webhook.port }}
              name: http-webhook
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
