apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "{{ include "nasp-webhook-controller.fullname" . }}"
  namespace: {{ .Release.Namespace }}
webhooks:
- name: config-injector.nasp.k8s.cisco.com
  objectSelector:
    matchExpressions:
    - key: "nasp.k8s.cisco.com/inject"
      operator: In
      values:
      - "true"
  clientConfig:
    service:
      name: "{{ include "nasp-webhook-controller.fullname" . }}"
      namespace: {{ .Release.Namespace }}
      path: /mutate-pod
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30
  admissionReviewVersions:
    - v1
