// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package request

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	typesbytes "github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var creatableRenewersPrincipalType = fields.Context{
	SpecName:                    "PrincipalType",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var creatableRenewersPrincipalName = fields.Context{
	SpecName:                    "PrincipalName",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}

type CreatableRenewers struct {
	unknownTaggedFields []fields.RawTaggedField
	principalType       fields.NullableString
	principalName       fields.NullableString
	isNil               bool
}

func (o *CreatableRenewers) PrincipalType() fields.NullableString {
	return o.principalType
}

func (o *CreatableRenewers) SetPrincipalType(val fields.NullableString) {
	o.isNil = false
	o.principalType = val
}

func (o *CreatableRenewers) PrincipalName() fields.NullableString {
	return o.principalName
}

func (o *CreatableRenewers) SetPrincipalName(val fields.NullableString) {
	o.isNil = false
	o.principalName = val
}

func (o *CreatableRenewers) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *CreatableRenewers) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *CreatableRenewers) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	principalTypeField := fields.String{Context: creatableRenewersPrincipalType}
	if err := principalTypeField.Read(buf, version, &o.principalType); err != nil {
		return errors.WrapIf(err, "couldn't set \"principalType\" field")
	}

	principalNameField := fields.String{Context: creatableRenewersPrincipalName}
	if err := principalNameField.Read(buf, version, &o.principalName); err != nil {
		return errors.WrapIf(err, "couldn't set \"principalName\" field")
	}

	// process tagged fields

	if version < CreatableRenewersLowestSupportedFlexVersion() || version > CreatableRenewersHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *CreatableRenewers) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	principalTypeField := fields.String{Context: creatableRenewersPrincipalType}
	if err := principalTypeField.Write(buf, version, o.principalType); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"principalType\" field")
	}
	principalNameField := fields.String{Context: creatableRenewersPrincipalName}
	if err := principalNameField.Write(buf, version, o.principalName); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"principalName\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < CreatableRenewersLowestSupportedFlexVersion() || version > CreatableRenewersHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *CreatableRenewers) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *CreatableRenewers) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 3)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.principalType); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"principalType\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.principalName); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"principalName\""), b}, []byte(": ")))
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *CreatableRenewers) IsNil() bool {
	return o.isNil
}

func (o *CreatableRenewers) Clear() {
	o.Release()
	o.isNil = true

	o.unknownTaggedFields = nil
}

func (o *CreatableRenewers) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.principalType.SetValue("")
	o.principalName.SetValue("")

	o.isNil = false
}

func (o *CreatableRenewers) Equal(that *CreatableRenewers) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if !o.principalType.Equal(&that.principalType) {
		return false
	}
	if !o.principalName.Equal(&that.principalName) {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *CreatableRenewers) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	principalTypeField := fields.String{Context: creatableRenewersPrincipalType}
	fieldSize, err = principalTypeField.SizeInBytes(version, o.principalType)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"principalType\" field")
	}
	size += fieldSize

	principalNameField := fields.String{Context: creatableRenewersPrincipalName}
	fieldSize, err = principalNameField.SizeInBytes(version, o.principalName)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"principalName\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < CreatableRenewersLowestSupportedFlexVersion() || version > CreatableRenewersHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *CreatableRenewers) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.principalType.Release()
	o.principalName.Release()
}

func (o *CreatableRenewers) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *CreatableRenewers) validateNonIgnorableFields(version int16) error {
	return nil
}

func CreatableRenewersLowestSupportedVersion() int16 {
	return 0
}

func CreatableRenewersHighestSupportedVersion() int16 {
	return 32767
}

func CreatableRenewersLowestSupportedFlexVersion() int16 {
	return 2
}

func CreatableRenewersHighestSupportedFlexVersion() int16 {
	return 32767
}

func CreatableRenewersDefault() CreatableRenewers {
	var d CreatableRenewers
	d.SetDefault()

	return d
}
