// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package deleteaclsfilterresult

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	typesbytes "github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var deleteAclsMatchingAclErrorCode = fields.Context{
	SpecName:                    "ErrorCode",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclErrorMessage = fields.Context{
	SpecName:                        "ErrorMessage",
	LowestSupportedVersion:          0,
	HighestSupportedVersion:         32767,
	LowestSupportedFlexVersion:      2,
	HighestSupportedFlexVersion:     32767,
	LowestSupportedNullableVersion:  0,
	HighestSupportedNullableVersion: 32767,
}
var deleteAclsMatchingAclResourceType = fields.Context{
	SpecName:                    "ResourceType",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclResourceName = fields.Context{
	SpecName:                    "ResourceName",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclPatternType = fields.Context{
	SpecName:                    "PatternType",
	CustomDefaultValue:          int8(3),
	LowestSupportedVersion:      1,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclPrincipal = fields.Context{
	SpecName:                    "Principal",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclHost = fields.Context{
	SpecName:                    "Host",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclOperation = fields.Context{
	SpecName:                    "Operation",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}
var deleteAclsMatchingAclPermissionType = fields.Context{
	SpecName:                    "PermissionType",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  2,
	HighestSupportedFlexVersion: 32767,
}

type DeleteAclsMatchingAcl struct {
	unknownTaggedFields []fields.RawTaggedField
	errorMessage        fields.NullableString
	resourceName        fields.NullableString
	principal           fields.NullableString
	host                fields.NullableString
	errorCode           int16
	resourceType        int8
	patternType         int8
	operation           int8
	permissionType      int8
	isNil               bool
}

func (o *DeleteAclsMatchingAcl) ErrorCode() int16 {
	return o.errorCode
}

func (o *DeleteAclsMatchingAcl) SetErrorCode(val int16) {
	o.isNil = false
	o.errorCode = val
}

func (o *DeleteAclsMatchingAcl) ErrorMessage() fields.NullableString {
	return o.errorMessage
}

func (o *DeleteAclsMatchingAcl) SetErrorMessage(val fields.NullableString) {
	o.isNil = false
	o.errorMessage = val
}

func (o *DeleteAclsMatchingAcl) ResourceType() int8 {
	return o.resourceType
}

func (o *DeleteAclsMatchingAcl) SetResourceType(val int8) {
	o.isNil = false
	o.resourceType = val
}

func (o *DeleteAclsMatchingAcl) ResourceName() fields.NullableString {
	return o.resourceName
}

func (o *DeleteAclsMatchingAcl) SetResourceName(val fields.NullableString) {
	o.isNil = false
	o.resourceName = val
}

func (o *DeleteAclsMatchingAcl) PatternType() int8 {
	return o.patternType
}

func (o *DeleteAclsMatchingAcl) SetPatternType(val int8) {
	o.isNil = false
	o.patternType = val
}

func (o *DeleteAclsMatchingAcl) Principal() fields.NullableString {
	return o.principal
}

func (o *DeleteAclsMatchingAcl) SetPrincipal(val fields.NullableString) {
	o.isNil = false
	o.principal = val
}

func (o *DeleteAclsMatchingAcl) Host() fields.NullableString {
	return o.host
}

func (o *DeleteAclsMatchingAcl) SetHost(val fields.NullableString) {
	o.isNil = false
	o.host = val
}

func (o *DeleteAclsMatchingAcl) Operation() int8 {
	return o.operation
}

func (o *DeleteAclsMatchingAcl) SetOperation(val int8) {
	o.isNil = false
	o.operation = val
}

func (o *DeleteAclsMatchingAcl) PermissionType() int8 {
	return o.permissionType
}

func (o *DeleteAclsMatchingAcl) SetPermissionType(val int8) {
	o.isNil = false
	o.permissionType = val
}

func (o *DeleteAclsMatchingAcl) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *DeleteAclsMatchingAcl) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *DeleteAclsMatchingAcl) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	errorCodeField := fields.Int16{Context: deleteAclsMatchingAclErrorCode}
	if err := errorCodeField.Read(buf, version, &o.errorCode); err != nil {
		return errors.WrapIf(err, "couldn't set \"errorCode\" field")
	}

	errorMessageField := fields.String{Context: deleteAclsMatchingAclErrorMessage}
	if err := errorMessageField.Read(buf, version, &o.errorMessage); err != nil {
		return errors.WrapIf(err, "couldn't set \"errorMessage\" field")
	}

	resourceTypeField := fields.Int8{Context: deleteAclsMatchingAclResourceType}
	if err := resourceTypeField.Read(buf, version, &o.resourceType); err != nil {
		return errors.WrapIf(err, "couldn't set \"resourceType\" field")
	}

	resourceNameField := fields.String{Context: deleteAclsMatchingAclResourceName}
	if err := resourceNameField.Read(buf, version, &o.resourceName); err != nil {
		return errors.WrapIf(err, "couldn't set \"resourceName\" field")
	}

	patternTypeField := fields.Int8{Context: deleteAclsMatchingAclPatternType}
	if err := patternTypeField.Read(buf, version, &o.patternType); err != nil {
		return errors.WrapIf(err, "couldn't set \"patternType\" field")
	}

	principalField := fields.String{Context: deleteAclsMatchingAclPrincipal}
	if err := principalField.Read(buf, version, &o.principal); err != nil {
		return errors.WrapIf(err, "couldn't set \"principal\" field")
	}

	hostField := fields.String{Context: deleteAclsMatchingAclHost}
	if err := hostField.Read(buf, version, &o.host); err != nil {
		return errors.WrapIf(err, "couldn't set \"host\" field")
	}

	operationField := fields.Int8{Context: deleteAclsMatchingAclOperation}
	if err := operationField.Read(buf, version, &o.operation); err != nil {
		return errors.WrapIf(err, "couldn't set \"operation\" field")
	}

	permissionTypeField := fields.Int8{Context: deleteAclsMatchingAclPermissionType}
	if err := permissionTypeField.Read(buf, version, &o.permissionType); err != nil {
		return errors.WrapIf(err, "couldn't set \"permissionType\" field")
	}

	// process tagged fields

	if version < DeleteAclsMatchingAclLowestSupportedFlexVersion() || version > DeleteAclsMatchingAclHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *DeleteAclsMatchingAcl) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	errorCodeField := fields.Int16{Context: deleteAclsMatchingAclErrorCode}
	if err := errorCodeField.Write(buf, version, o.errorCode); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"errorCode\" field")
	}
	errorMessageField := fields.String{Context: deleteAclsMatchingAclErrorMessage}
	if err := errorMessageField.Write(buf, version, o.errorMessage); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"errorMessage\" field")
	}
	resourceTypeField := fields.Int8{Context: deleteAclsMatchingAclResourceType}
	if err := resourceTypeField.Write(buf, version, o.resourceType); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"resourceType\" field")
	}
	resourceNameField := fields.String{Context: deleteAclsMatchingAclResourceName}
	if err := resourceNameField.Write(buf, version, o.resourceName); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"resourceName\" field")
	}
	patternTypeField := fields.Int8{Context: deleteAclsMatchingAclPatternType}
	if err := patternTypeField.Write(buf, version, o.patternType); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"patternType\" field")
	}
	principalField := fields.String{Context: deleteAclsMatchingAclPrincipal}
	if err := principalField.Write(buf, version, o.principal); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"principal\" field")
	}
	hostField := fields.String{Context: deleteAclsMatchingAclHost}
	if err := hostField.Write(buf, version, o.host); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"host\" field")
	}
	operationField := fields.Int8{Context: deleteAclsMatchingAclOperation}
	if err := operationField.Write(buf, version, o.operation); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"operation\" field")
	}
	permissionTypeField := fields.Int8{Context: deleteAclsMatchingAclPermissionType}
	if err := permissionTypeField.Write(buf, version, o.permissionType); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"permissionType\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < DeleteAclsMatchingAclLowestSupportedFlexVersion() || version > DeleteAclsMatchingAclHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *DeleteAclsMatchingAcl) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *DeleteAclsMatchingAcl) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 10)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.errorCode); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"errorCode\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.errorMessage); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"errorMessage\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.resourceType); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"resourceType\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.resourceName); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"resourceName\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.patternType); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"patternType\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.principal); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"principal\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.host); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"host\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.operation); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"operation\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.permissionType); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"permissionType\""), b}, []byte(": ")))
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *DeleteAclsMatchingAcl) IsNil() bool {
	return o.isNil
}

func (o *DeleteAclsMatchingAcl) Clear() {
	o.Release()
	o.isNil = true

	o.unknownTaggedFields = nil
}

func (o *DeleteAclsMatchingAcl) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.errorCode = 0
	o.errorMessage.SetValue("")
	o.resourceType = 0
	o.resourceName.SetValue("")
	o.patternType = 3
	o.principal.SetValue("")
	o.host.SetValue("")
	o.operation = 0
	o.permissionType = 0

	o.isNil = false
}

func (o *DeleteAclsMatchingAcl) Equal(that *DeleteAclsMatchingAcl) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if o.errorCode != that.errorCode {
		return false
	}
	if !o.errorMessage.Equal(&that.errorMessage) {
		return false
	}
	if o.resourceType != that.resourceType {
		return false
	}
	if !o.resourceName.Equal(&that.resourceName) {
		return false
	}
	if o.patternType != that.patternType {
		return false
	}
	if !o.principal.Equal(&that.principal) {
		return false
	}
	if !o.host.Equal(&that.host) {
		return false
	}
	if o.operation != that.operation {
		return false
	}
	if o.permissionType != that.permissionType {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *DeleteAclsMatchingAcl) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	errorCodeField := fields.Int16{Context: deleteAclsMatchingAclErrorCode}
	fieldSize, err = errorCodeField.SizeInBytes(version, o.errorCode)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"errorCode\" field")
	}
	size += fieldSize

	errorMessageField := fields.String{Context: deleteAclsMatchingAclErrorMessage}
	fieldSize, err = errorMessageField.SizeInBytes(version, o.errorMessage)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"errorMessage\" field")
	}
	size += fieldSize

	resourceTypeField := fields.Int8{Context: deleteAclsMatchingAclResourceType}
	fieldSize, err = resourceTypeField.SizeInBytes(version, o.resourceType)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"resourceType\" field")
	}
	size += fieldSize

	resourceNameField := fields.String{Context: deleteAclsMatchingAclResourceName}
	fieldSize, err = resourceNameField.SizeInBytes(version, o.resourceName)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"resourceName\" field")
	}
	size += fieldSize

	patternTypeField := fields.Int8{Context: deleteAclsMatchingAclPatternType}
	fieldSize, err = patternTypeField.SizeInBytes(version, o.patternType)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"patternType\" field")
	}
	size += fieldSize

	principalField := fields.String{Context: deleteAclsMatchingAclPrincipal}
	fieldSize, err = principalField.SizeInBytes(version, o.principal)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"principal\" field")
	}
	size += fieldSize

	hostField := fields.String{Context: deleteAclsMatchingAclHost}
	fieldSize, err = hostField.SizeInBytes(version, o.host)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"host\" field")
	}
	size += fieldSize

	operationField := fields.Int8{Context: deleteAclsMatchingAclOperation}
	fieldSize, err = operationField.SizeInBytes(version, o.operation)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"operation\" field")
	}
	size += fieldSize

	permissionTypeField := fields.Int8{Context: deleteAclsMatchingAclPermissionType}
	fieldSize, err = permissionTypeField.SizeInBytes(version, o.permissionType)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"permissionType\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < DeleteAclsMatchingAclLowestSupportedFlexVersion() || version > DeleteAclsMatchingAclHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *DeleteAclsMatchingAcl) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.errorMessage.Release()
	o.resourceName.Release()
	o.principal.Release()
	o.host.Release()
}

func (o *DeleteAclsMatchingAcl) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *DeleteAclsMatchingAcl) validateNonIgnorableFields(version int16) error {
	if !deleteAclsMatchingAclPatternType.IsSupportedVersion(version) {
		if o.patternType != 3 {
			return errors.New(strings.Join([]string{"attempted to write non-default \"patternType\" at version", strconv.Itoa(int(version))}, " "))
		}
	}
	return nil
}

func DeleteAclsMatchingAclLowestSupportedVersion() int16 {
	return 0
}

func DeleteAclsMatchingAclHighestSupportedVersion() int16 {
	return 32767
}

func DeleteAclsMatchingAclLowestSupportedFlexVersion() int16 {
	return 2
}

func DeleteAclsMatchingAclHighestSupportedFlexVersion() int16 {
	return 32767
}

func DeleteAclsMatchingAclDefault() DeleteAclsMatchingAcl {
	var d DeleteAclsMatchingAcl
	d.SetDefault()

	return d
}
