{{- if and .Values.istio.meshGateway.enabled .Values.istio.meshGateway.withIstioOperator -}}
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  labels:
    app: {{ include "heimdall.fullname" . }}-gw
    istio.io/rev: {{ .Values.istio.revision }}
  name: {{ include "heimdall.fullname" . }}-gw
spec:
  deployment:
    podMetadata:
      labels:
        app: {{ include "heimdall.fullname" . }}-gw
  istioControlPlane:
    name: {{ .Values.istio.controlPlane }}
    namespace: {{ .Values.istio.controlPlaneNamespace }}
  runAsRoot: false
  service:
    externalTrafficPolicy: Local
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
      {{- if .Values.istio.meshGateway.nodePort }}
      nodePort: {{ .Values.istio.meshGateway.nodePort }}
      {{- end }}
    type: LoadBalancer
  type: ingress
{{- end }}
