{{- if .Values.istio.meshGateway.enabled -}}
apiVersion: servicemesh.cisco.com/v1alpha1
kind: IstioMeshGateway
metadata:
  labels:
    app: {{ include "heimdall.fullname" . }}-gw
    istio.io/rev: {{ .Values.istio.revision }}
  name: {{ include "heimdall.fullname" . }}-gw
spec:
  deployment:
    podMetadata:
      labels:
        app: {{ include "heimdall.fullname" . }}-gw
  istioControlPlane:
    name: {{ .Values.istio.controlPlane }}
    namespace: {{ .Values.istio.controlPlaneNamespace }}
  runAsRoot: false
  service:
    externalTrafficPolicy: Local
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
    ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
      {{- if .Values.istio.meshGateway.nodePort }}
      nodePort: {{ .Values.istio.meshGateway.nodePort }}
      {{- end }}
    type: LoadBalancer
  type: ingress
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "heimdall.fullname" . }}
spec:
  selector:
    gateway-name: {{ include "heimdall.fullname" . }}-gw
    gateway-type: ingress
  servers:
  - hosts:
    - '*'
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ include "heimdall.fullname" . }}
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "heimdall.fullname" . }}
spec:
  gateways:
  - {{ include "heimdall.fullname" . }}
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: {{ include "heimdall.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 8080
{{- end }}
