apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimdall.fullname" . }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: http-metrics
    - port: {{ .Values.healthz.port }}
      targetPort: healthz
      protocol: TCP
      name: http-healthz
    - port: 443
      targetPort: http-webhook
      protocol: TCP
      name: http-webhook
  selector:
    {{- include "heimdall.selectorLabels" . | nindent 4 }}
