apiVersion: v1
kind: Service
metadata:
  name: {{ include "bifrost.fullname" . }}
  labels:
    {{- include "bifrost.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tcp-control
      protocol: TCP
      name: tcp-control
  selector:
    {{- include "bifrost.selectorLabels" . | nindent 4 }}
