{{- if .Values.istio.meshGateway.enabled }}
{{- $ca := genCA "nasptestca" 365 }}
{{- $dbtlscert := genSignedCert (include "heimdall.name" .) nil (list (include "heimdall.name" .)) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . | quote }}
  namespace: {{ $.Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $dbtlscert.Cert | b64enc | quote }}
  tls.key: {{ $dbtlscert.Key | b64enc | quote }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
{{- end }}
