approved = [
  "mit",
  "apache-2.0",
  "bsd-3-clause",
  "bsd-2-clause",
  "mpl-2.0",
]

ignored = [
  "wwwin-github.cisco.com/eti/kafka-protocol-go/pkg"
]

[header]
ignoreFiles = [
]

template = """Copyright (c) :YEAR: Cisco and/or its affiliates. All rights reserved.
"""
