// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package alteruserscramcredentials

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/messages/alteruserscramcredentials/request"
	typesbytes "github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var requestDeletions = fields.Context{
	SpecName:                    "Deletions",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}
var requestUpsertions = fields.Context{
	SpecName:                    "Upsertions",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}

type Request struct {

	// The SCRAM credentials to remove.
	deletions []request.ScramCredentialDeletion
	// The SCRAM credentials to update/insert.
	upsertions          []request.ScramCredentialUpsertion
	unknownTaggedFields []fields.RawTaggedField

	isNil bool
}

func (o *Request) Deletions() []request.ScramCredentialDeletion {
	return o.deletions
}

func (o *Request) SetDeletions(val []request.ScramCredentialDeletion) {
	o.isNil = false
	o.deletions = val
}

func (o *Request) Upsertions() []request.ScramCredentialUpsertion {
	return o.upsertions
}

func (o *Request) SetUpsertions(val []request.ScramCredentialUpsertion) {
	o.isNil = false
	o.upsertions = val
}

func (o *Request) ApiKey() int16 {
	return 51
}

func (o *Request) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *Request) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *Request) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	deletionsField := fields.ArrayOfStruct[request.ScramCredentialDeletion, *request.ScramCredentialDeletion]{Context: requestDeletions}
	deletions, err := deletionsField.Read(buf, version)
	if err != nil {
		return errors.WrapIf(err, "couldn't set \"deletions\" field")
	}
	o.deletions = deletions

	upsertionsField := fields.ArrayOfStruct[request.ScramCredentialUpsertion, *request.ScramCredentialUpsertion]{Context: requestUpsertions}
	upsertions, err := upsertionsField.Read(buf, version)
	if err != nil {
		return errors.WrapIf(err, "couldn't set \"upsertions\" field")
	}
	o.upsertions = upsertions

	// process tagged fields

	if version < RequestLowestSupportedFlexVersion() || version > RequestHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *Request) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	deletionsField := fields.ArrayOfStruct[request.ScramCredentialDeletion, *request.ScramCredentialDeletion]{Context: requestDeletions}
	if err := deletionsField.Write(buf, version, o.deletions); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"deletions\" field")
	}

	upsertionsField := fields.ArrayOfStruct[request.ScramCredentialUpsertion, *request.ScramCredentialUpsertion]{Context: requestUpsertions}
	if err := upsertionsField.Write(buf, version, o.upsertions); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"upsertions\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < RequestLowestSupportedFlexVersion() || version > RequestHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *Request) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *Request) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 3)
	if b, err := fields.ArrayOfStructMarshalJSON("deletions", o.deletions); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}
	if b, err := fields.ArrayOfStructMarshalJSON("upsertions", o.upsertions); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *Request) IsNil() bool {
	return o.isNil
}

func (o *Request) Clear() {
	o.Release()
	o.isNil = true

	o.deletions = nil
	o.upsertions = nil
	o.unknownTaggedFields = nil
}

func (o *Request) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	for i := range o.deletions {
		o.deletions[i].Release()
	}
	o.deletions = nil
	for i := range o.upsertions {
		o.upsertions[i].Release()
	}
	o.upsertions = nil

	o.isNil = false
}

func (o *Request) Equal(that *Request) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if len(o.deletions) != len(that.deletions) {
		return false
	}
	for i := range o.deletions {
		if !o.deletions[i].Equal(&that.deletions[i]) {
			return false
		}
	}
	if len(o.upsertions) != len(that.upsertions) {
		return false
	}
	for i := range o.upsertions {
		if !o.upsertions[i].Equal(&that.upsertions[i]) {
			return false
		}
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *Request) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	deletionsField := fields.ArrayOfStruct[request.ScramCredentialDeletion, *request.ScramCredentialDeletion]{Context: requestDeletions}
	fieldSize, err = deletionsField.SizeInBytes(version, o.deletions)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"deletions\" field")
	}
	size += fieldSize

	upsertionsField := fields.ArrayOfStruct[request.ScramCredentialUpsertion, *request.ScramCredentialUpsertion]{Context: requestUpsertions}
	fieldSize, err = upsertionsField.SizeInBytes(version, o.upsertions)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"upsertions\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < RequestLowestSupportedFlexVersion() || version > RequestHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *Request) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	for i := range o.deletions {
		o.deletions[i].Release()
	}
	o.deletions = nil
	for i := range o.upsertions {
		o.upsertions[i].Release()
	}
	o.upsertions = nil
}

func (o *Request) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *Request) validateNonIgnorableFields(version int16) error {
	return nil
}

func RequestLowestSupportedVersion() int16 {
	return 0
}

func RequestHighestSupportedVersion() int16 {
	return 0
}

func RequestLowestSupportedFlexVersion() int16 {
	return 0
}

func RequestHighestSupportedFlexVersion() int16 {
	return 32767
}

func RequestDefault() Request {
	var d Request
	d.SetDefault()

	return d
}
