// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package request

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/pools"
	typesbytes "github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var syncGroupRequestAssignmentMemberId = fields.Context{
	SpecName:                    "MemberId",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var syncGroupRequestAssignmentAssignment = fields.Context{
	SpecName:                    "Assignment",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}

type SyncGroupRequestAssignment struct {
	assignment          []byte
	unknownTaggedFields []fields.RawTaggedField
	memberId            fields.NullableString
	isNil               bool
}

func (o *SyncGroupRequestAssignment) MemberId() fields.NullableString {
	return o.memberId
}

func (o *SyncGroupRequestAssignment) SetMemberId(val fields.NullableString) {
	o.isNil = false
	o.memberId = val
}

func (o *SyncGroupRequestAssignment) Assignment() []byte {
	return o.assignment
}

func (o *SyncGroupRequestAssignment) SetAssignment(val []byte) {
	o.isNil = false
	o.assignment = val
}

func (o *SyncGroupRequestAssignment) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *SyncGroupRequestAssignment) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *SyncGroupRequestAssignment) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	memberIdField := fields.String{Context: syncGroupRequestAssignmentMemberId}
	if err := memberIdField.Read(buf, version, &o.memberId); err != nil {
		return errors.WrapIf(err, "couldn't set \"memberId\" field")
	}

	assignmentField := fields.Bytes{Context: syncGroupRequestAssignmentAssignment}
	if err := assignmentField.Read(buf, version, &o.assignment); err != nil {
		return errors.WrapIf(err, "couldn't set \"assignment\" field")
	}

	// process tagged fields

	if version < SyncGroupRequestAssignmentLowestSupportedFlexVersion() || version > SyncGroupRequestAssignmentHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *SyncGroupRequestAssignment) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	memberIdField := fields.String{Context: syncGroupRequestAssignmentMemberId}
	if err := memberIdField.Write(buf, version, o.memberId); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"memberId\" field")
	}
	assignmentField := fields.Bytes{Context: syncGroupRequestAssignmentAssignment}
	if err := assignmentField.Write(buf, version, o.assignment); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"assignment\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < SyncGroupRequestAssignmentLowestSupportedFlexVersion() || version > SyncGroupRequestAssignmentHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *SyncGroupRequestAssignment) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *SyncGroupRequestAssignment) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 3)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.memberId); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"memberId\""), b}, []byte(": ")))
	}
	if b, err := fields.BytesMarshalJSON("assignment", o.assignment); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *SyncGroupRequestAssignment) IsNil() bool {
	return o.isNil
}

func (o *SyncGroupRequestAssignment) Clear() {
	o.Release()
	o.isNil = true

	o.unknownTaggedFields = nil
}

func (o *SyncGroupRequestAssignment) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.memberId.SetValue("")
	if o.assignment != nil {
		pools.ReleaseByteSlice(o.assignment)
	}
	o.assignment = nil

	o.isNil = false
}

func (o *SyncGroupRequestAssignment) Equal(that *SyncGroupRequestAssignment) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if !o.memberId.Equal(&that.memberId) {
		return false
	}
	if !bytes.Equal(o.assignment, that.assignment) {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *SyncGroupRequestAssignment) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	memberIdField := fields.String{Context: syncGroupRequestAssignmentMemberId}
	fieldSize, err = memberIdField.SizeInBytes(version, o.memberId)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"memberId\" field")
	}
	size += fieldSize

	assignmentField := fields.Bytes{Context: syncGroupRequestAssignmentAssignment}
	fieldSize, err = assignmentField.SizeInBytes(version, o.assignment)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"assignment\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < SyncGroupRequestAssignmentLowestSupportedFlexVersion() || version > SyncGroupRequestAssignmentHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *SyncGroupRequestAssignment) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.memberId.Release()
	if o.assignment != nil {
		pools.ReleaseByteSlice(o.assignment)
	}
}

func (o *SyncGroupRequestAssignment) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *SyncGroupRequestAssignment) validateNonIgnorableFields(version int16) error {
	return nil
}

func SyncGroupRequestAssignmentLowestSupportedVersion() int16 {
	return 0
}

func SyncGroupRequestAssignmentHighestSupportedVersion() int16 {
	return 32767
}

func SyncGroupRequestAssignmentLowestSupportedFlexVersion() int16 {
	return 4
}

func SyncGroupRequestAssignmentHighestSupportedFlexVersion() int16 {
	return 32767
}

func SyncGroupRequestAssignmentDefault() SyncGroupRequestAssignment {
	var d SyncGroupRequestAssignment
	d.SetDefault()

	return d
}
