// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package partitionresponse

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	typesbytes "github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/nasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var producerStateProducerId = fields.Context{
	SpecName:                    "ProducerId",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}
var producerStateProducerEpoch = fields.Context{
	SpecName:                    "ProducerEpoch",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}
var producerStateLastSequence = fields.Context{
	SpecName:                    "LastSequence",
	CustomDefaultValue:          int32(-1),
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}
var producerStateLastTimestamp = fields.Context{
	SpecName:                    "LastTimestamp",
	CustomDefaultValue:          int64(-1),
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}
var producerStateCoordinatorEpoch = fields.Context{
	SpecName:                    "CoordinatorEpoch",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}
var producerStateCurrentTxnStartOffset = fields.Context{
	SpecName:                    "CurrentTxnStartOffset",
	CustomDefaultValue:          int64(-1),
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  0,
	HighestSupportedFlexVersion: 32767,
}

type ProducerState struct {
	unknownTaggedFields   []fields.RawTaggedField
	producerId            int64
	lastTimestamp         int64
	currentTxnStartOffset int64
	producerEpoch         int32
	lastSequence          int32
	coordinatorEpoch      int32
	isNil                 bool
}

func (o *ProducerState) ProducerId() int64 {
	return o.producerId
}

func (o *ProducerState) SetProducerId(val int64) {
	o.isNil = false
	o.producerId = val
}

func (o *ProducerState) ProducerEpoch() int32 {
	return o.producerEpoch
}

func (o *ProducerState) SetProducerEpoch(val int32) {
	o.isNil = false
	o.producerEpoch = val
}

func (o *ProducerState) LastSequence() int32 {
	return o.lastSequence
}

func (o *ProducerState) SetLastSequence(val int32) {
	o.isNil = false
	o.lastSequence = val
}

func (o *ProducerState) LastTimestamp() int64 {
	return o.lastTimestamp
}

func (o *ProducerState) SetLastTimestamp(val int64) {
	o.isNil = false
	o.lastTimestamp = val
}

func (o *ProducerState) CoordinatorEpoch() int32 {
	return o.coordinatorEpoch
}

func (o *ProducerState) SetCoordinatorEpoch(val int32) {
	o.isNil = false
	o.coordinatorEpoch = val
}

func (o *ProducerState) CurrentTxnStartOffset() int64 {
	return o.currentTxnStartOffset
}

func (o *ProducerState) SetCurrentTxnStartOffset(val int64) {
	o.isNil = false
	o.currentTxnStartOffset = val
}

func (o *ProducerState) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *ProducerState) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *ProducerState) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	producerIdField := fields.Int64{Context: producerStateProducerId}
	if err := producerIdField.Read(buf, version, &o.producerId); err != nil {
		return errors.WrapIf(err, "couldn't set \"producerId\" field")
	}

	producerEpochField := fields.Int32{Context: producerStateProducerEpoch}
	if err := producerEpochField.Read(buf, version, &o.producerEpoch); err != nil {
		return errors.WrapIf(err, "couldn't set \"producerEpoch\" field")
	}

	lastSequenceField := fields.Int32{Context: producerStateLastSequence}
	if err := lastSequenceField.Read(buf, version, &o.lastSequence); err != nil {
		return errors.WrapIf(err, "couldn't set \"lastSequence\" field")
	}

	lastTimestampField := fields.Int64{Context: producerStateLastTimestamp}
	if err := lastTimestampField.Read(buf, version, &o.lastTimestamp); err != nil {
		return errors.WrapIf(err, "couldn't set \"lastTimestamp\" field")
	}

	coordinatorEpochField := fields.Int32{Context: producerStateCoordinatorEpoch}
	if err := coordinatorEpochField.Read(buf, version, &o.coordinatorEpoch); err != nil {
		return errors.WrapIf(err, "couldn't set \"coordinatorEpoch\" field")
	}

	currentTxnStartOffsetField := fields.Int64{Context: producerStateCurrentTxnStartOffset}
	if err := currentTxnStartOffsetField.Read(buf, version, &o.currentTxnStartOffset); err != nil {
		return errors.WrapIf(err, "couldn't set \"currentTxnStartOffset\" field")
	}

	// process tagged fields

	if version < ProducerStateLowestSupportedFlexVersion() || version > ProducerStateHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *ProducerState) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	producerIdField := fields.Int64{Context: producerStateProducerId}
	if err := producerIdField.Write(buf, version, o.producerId); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"producerId\" field")
	}
	producerEpochField := fields.Int32{Context: producerStateProducerEpoch}
	if err := producerEpochField.Write(buf, version, o.producerEpoch); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"producerEpoch\" field")
	}
	lastSequenceField := fields.Int32{Context: producerStateLastSequence}
	if err := lastSequenceField.Write(buf, version, o.lastSequence); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"lastSequence\" field")
	}
	lastTimestampField := fields.Int64{Context: producerStateLastTimestamp}
	if err := lastTimestampField.Write(buf, version, o.lastTimestamp); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"lastTimestamp\" field")
	}
	coordinatorEpochField := fields.Int32{Context: producerStateCoordinatorEpoch}
	if err := coordinatorEpochField.Write(buf, version, o.coordinatorEpoch); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"coordinatorEpoch\" field")
	}
	currentTxnStartOffsetField := fields.Int64{Context: producerStateCurrentTxnStartOffset}
	if err := currentTxnStartOffsetField.Write(buf, version, o.currentTxnStartOffset); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"currentTxnStartOffset\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < ProducerStateLowestSupportedFlexVersion() || version > ProducerStateHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *ProducerState) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *ProducerState) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 7)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.producerId); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"producerId\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.producerEpoch); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"producerEpoch\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.lastSequence); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"lastSequence\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.lastTimestamp); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"lastTimestamp\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.coordinatorEpoch); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"coordinatorEpoch\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.currentTxnStartOffset); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"currentTxnStartOffset\""), b}, []byte(": ")))
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *ProducerState) IsNil() bool {
	return o.isNil
}

func (o *ProducerState) Clear() {
	o.Release()
	o.isNil = true

	o.unknownTaggedFields = nil
}

func (o *ProducerState) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.producerId = 0
	o.producerEpoch = 0
	o.lastSequence = -1
	o.lastTimestamp = -1
	o.coordinatorEpoch = 0
	o.currentTxnStartOffset = -1

	o.isNil = false
}

func (o *ProducerState) Equal(that *ProducerState) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if o.producerId != that.producerId {
		return false
	}
	if o.producerEpoch != that.producerEpoch {
		return false
	}
	if o.lastSequence != that.lastSequence {
		return false
	}
	if o.lastTimestamp != that.lastTimestamp {
		return false
	}
	if o.coordinatorEpoch != that.coordinatorEpoch {
		return false
	}
	if o.currentTxnStartOffset != that.currentTxnStartOffset {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *ProducerState) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	producerIdField := fields.Int64{Context: producerStateProducerId}
	fieldSize, err = producerIdField.SizeInBytes(version, o.producerId)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"producerId\" field")
	}
	size += fieldSize

	producerEpochField := fields.Int32{Context: producerStateProducerEpoch}
	fieldSize, err = producerEpochField.SizeInBytes(version, o.producerEpoch)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"producerEpoch\" field")
	}
	size += fieldSize

	lastSequenceField := fields.Int32{Context: producerStateLastSequence}
	fieldSize, err = lastSequenceField.SizeInBytes(version, o.lastSequence)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"lastSequence\" field")
	}
	size += fieldSize

	lastTimestampField := fields.Int64{Context: producerStateLastTimestamp}
	fieldSize, err = lastTimestampField.SizeInBytes(version, o.lastTimestamp)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"lastTimestamp\" field")
	}
	size += fieldSize

	coordinatorEpochField := fields.Int32{Context: producerStateCoordinatorEpoch}
	fieldSize, err = coordinatorEpochField.SizeInBytes(version, o.coordinatorEpoch)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"coordinatorEpoch\" field")
	}
	size += fieldSize

	currentTxnStartOffsetField := fields.Int64{Context: producerStateCurrentTxnStartOffset}
	fieldSize, err = currentTxnStartOffsetField.SizeInBytes(version, o.currentTxnStartOffset)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"currentTxnStartOffset\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < ProducerStateLowestSupportedFlexVersion() || version > ProducerStateHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *ProducerState) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

}

func (o *ProducerState) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *ProducerState) validateNonIgnorableFields(version int16) error {
	return nil
}

func ProducerStateLowestSupportedVersion() int16 {
	return 0
}

func ProducerStateHighestSupportedVersion() int16 {
	return 32767
}

func ProducerStateLowestSupportedFlexVersion() int16 {
	return 0
}

func ProducerStateHighestSupportedFlexVersion() int16 {
	return 32767
}

func ProducerStateDefault() ProducerState {
	var d ProducerState
	d.SetDefault()

	return d
}
