apiVersion: v1
kind: ServiceAccount
metadata:
  name: heimdall
  namespace: heimdall
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heimdall-configmaps
  namespace: heimdall
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heimdall-configmaps
  namespace: heimdall
subjects:
- kind: ServiceAccount
  name: heimdall
  namespace: heimdall
roleRef:
  kind: Role
  name: heimdall-configmaps
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heimdall-istio
rules:
- apiGroups: [""]
  resources: ["services", "pods", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["servicemesh.cisco.com"]
  resources: ["istiomeshgateways"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heimdall-istio
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: heimdall
  namespace: heimdall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heimdall-istio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: heimdall-cluster-registry
rules:
- apiGroups: ["clusterregistry.k8s.cisco.com"]
  resources: ["clusters"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: heimdall-cluster-registry
subjects:
- kind: ServiceAccount
  name: heimdall
  namespace: heimdall
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heimdall-cluster-registry
