// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package createpartitionstopic

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	typesbytes "github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var createPartitionsAssignmentBrokerIds = fields.Context{
	SpecName:                        "BrokerIds",
	LowestSupportedVersion:          0,
	HighestSupportedVersion:         32767,
	LowestSupportedFlexVersion:      2,
	HighestSupportedFlexVersion:     32767,
	LowestSupportedNullableVersion:  0,
	HighestSupportedNullableVersion: 32767,
}

type CreatePartitionsAssignment struct {

	// The assigned broker IDs.
	brokerIds           []int32
	unknownTaggedFields []fields.RawTaggedField

	isNil bool
}

func (o *CreatePartitionsAssignment) BrokerIds() []int32 {
	return o.brokerIds
}

func (o *CreatePartitionsAssignment) SetBrokerIds(val []int32) {
	o.isNil = false
	o.brokerIds = val
}

func (o *CreatePartitionsAssignment) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *CreatePartitionsAssignment) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *CreatePartitionsAssignment) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	brokerIdsField := fields.Array[int32, *fields.Int32]{
		Context:          createPartitionsAssignmentBrokerIds,
		ElementProcessor: &fields.Int32{Context: createPartitionsAssignmentBrokerIds}}

	brokerIds, err := brokerIdsField.Read(buf, version)
	if err != nil {
		return errors.WrapIf(err, "couldn't set \"brokerIds\" field")
	}
	o.brokerIds = brokerIds

	// process tagged fields

	if version < CreatePartitionsAssignmentLowestSupportedFlexVersion() || version > CreatePartitionsAssignmentHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *CreatePartitionsAssignment) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	brokerIdsField := fields.Array[int32, *fields.Int32]{
		Context:          createPartitionsAssignmentBrokerIds,
		ElementProcessor: &fields.Int32{Context: createPartitionsAssignmentBrokerIds}}
	if err := brokerIdsField.Write(buf, version, o.brokerIds); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"brokerIds\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < CreatePartitionsAssignmentLowestSupportedFlexVersion() || version > CreatePartitionsAssignmentHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *CreatePartitionsAssignment) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *CreatePartitionsAssignment) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 2)
	if b, err := fields.ArrayMarshalJSON("brokerIds", o.brokerIds); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *CreatePartitionsAssignment) IsNil() bool {
	return o.isNil
}

func (o *CreatePartitionsAssignment) Clear() {
	o.Release()
	o.isNil = true

	o.brokerIds = nil
	o.unknownTaggedFields = nil
}

func (o *CreatePartitionsAssignment) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.brokerIds = nil

	o.isNil = false
}

func (o *CreatePartitionsAssignment) Equal(that *CreatePartitionsAssignment) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if !fields.PrimitiveTypeSliceEqual(o.brokerIds, that.brokerIds) {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *CreatePartitionsAssignment) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	brokerIdsField := fields.Array[int32, *fields.Int32]{
		Context:          createPartitionsAssignmentBrokerIds,
		ElementProcessor: &fields.Int32{Context: createPartitionsAssignmentBrokerIds}}
	fieldSize, err = brokerIdsField.SizeInBytes(version, o.brokerIds)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"brokerIds\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < CreatePartitionsAssignmentLowestSupportedFlexVersion() || version > CreatePartitionsAssignmentHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *CreatePartitionsAssignment) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.brokerIds = nil
}

func (o *CreatePartitionsAssignment) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *CreatePartitionsAssignment) validateNonIgnorableFields(version int16) error {
	return nil
}

func CreatePartitionsAssignmentLowestSupportedVersion() int16 {
	return 0
}

func CreatePartitionsAssignmentHighestSupportedVersion() int16 {
	return 32767
}

func CreatePartitionsAssignmentLowestSupportedFlexVersion() int16 {
	return 2
}

func CreatePartitionsAssignmentHighestSupportedFlexVersion() int16 {
	return 32767
}

func CreatePartitionsAssignmentDefault() CreatePartitionsAssignment {
	var d CreatePartitionsAssignment
	d.SetDefault()

	return d
}
