apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-nasp-example
  labels:
    app: spring-boot-nasp-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-nasp-example
  template:
    metadata:
      labels:
        app: spring-boot-nasp-example
    spec:
      containers:
        - name: app
          image: docker.io/library/spring-boot-nasp-example:1.0-SNAPSHOT
          env:
            - name: NASP_HEIMDALLURL
              value: http://heimdall.heimdall:8080/config
          ports:
            - containerPort: 80