apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nasp-webhook-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nasp-webhook-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nasp-webhook-controller.fullname" . }}
  labels:
    {{- include "nasp-webhook-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - '*'
- apiGroups: ["clusterregistry.k8s.cisco.com"]
  resources: ["*"]
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nasp-webhook-controller.fullname" . }}
  labels:
    {{- include "nasp-webhook-controller.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "nasp-webhook-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "nasp-webhook-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
