// Code generated by kafka-protocol-go. DO NOT EDIT.

// Copyright (c) 2023 Cisco and/or its affiliates. All rights reserved.
//
//	Licensed under the Apache License, Version 2.0 (the "License");
//	you may not use this file except in compliance with the License.
//	You may obtain a copy of the License at
//
//	     https://www.apache.org/licenses/LICENSE-2.0
//
//	Unless required by applicable law or agreed to in writing, software
//	distributed under the License is distributed on an "AS IS" BASIS,
//	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//	See the License for the specific language governing permissions and
//	limitations under the License.
package describeconfigsresult

import (
	"bytes"
	"strconv"
	"strings"

	"emperror.dev/errors"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/messages/describeconfigs/response/describeconfigsresult/describeconfigsresourceresult"
	typesbytes "github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/bytes"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/fields"
	"github.com/cisco-open/libnasp/components/kafka-protocol-go/pkg/protocol/types/varint"
)

var describeConfigsResourceResultName = fields.Context{
	SpecName:                    "Name",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultValue = fields.Context{
	SpecName:                        "Value",
	LowestSupportedVersion:          0,
	HighestSupportedVersion:         32767,
	LowestSupportedFlexVersion:      4,
	HighestSupportedFlexVersion:     32767,
	LowestSupportedNullableVersion:  0,
	HighestSupportedNullableVersion: 32767,
}
var describeConfigsResourceResultReadOnly = fields.Context{
	SpecName:                    "ReadOnly",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultIsDefault = fields.Context{
	SpecName:                    "IsDefault",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     0,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultConfigSource = fields.Context{
	SpecName:                    "ConfigSource",
	CustomDefaultValue:          int8(-1),
	LowestSupportedVersion:      1,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultIsSensitive = fields.Context{
	SpecName:                    "IsSensitive",
	LowestSupportedVersion:      0,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultSynonyms = fields.Context{
	SpecName:                    "Synonyms",
	LowestSupportedVersion:      1,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultConfigType = fields.Context{
	SpecName:                    "ConfigType",
	LowestSupportedVersion:      3,
	HighestSupportedVersion:     32767,
	LowestSupportedFlexVersion:  4,
	HighestSupportedFlexVersion: 32767,
}
var describeConfigsResourceResultDocumentation = fields.Context{
	SpecName:                        "Documentation",
	LowestSupportedVersion:          3,
	HighestSupportedVersion:         32767,
	LowestSupportedFlexVersion:      4,
	HighestSupportedFlexVersion:     32767,
	LowestSupportedNullableVersion:  0,
	HighestSupportedNullableVersion: 32767,
}

type DescribeConfigsResourceResult struct {
	synonyms            []describeconfigsresourceresult.DescribeConfigsSynonym
	unknownTaggedFields []fields.RawTaggedField
	name                fields.NullableString
	value               fields.NullableString
	documentation       fields.NullableString
	readOnly            bool
	isDefault           bool
	configSource        int8
	isSensitive         bool
	configType          int8
	isNil               bool
}

func (o *DescribeConfigsResourceResult) Name() fields.NullableString {
	return o.name
}

func (o *DescribeConfigsResourceResult) SetName(val fields.NullableString) {
	o.isNil = false
	o.name = val
}

func (o *DescribeConfigsResourceResult) Value() fields.NullableString {
	return o.value
}

func (o *DescribeConfigsResourceResult) SetValue(val fields.NullableString) {
	o.isNil = false
	o.value = val
}

func (o *DescribeConfigsResourceResult) ReadOnly() bool {
	return o.readOnly
}

func (o *DescribeConfigsResourceResult) SetReadOnly(val bool) {
	o.isNil = false
	o.readOnly = val
}

func (o *DescribeConfigsResourceResult) IsDefault() bool {
	return o.isDefault
}

func (o *DescribeConfigsResourceResult) SetIsDefault(val bool) {
	o.isNil = false
	o.isDefault = val
}

func (o *DescribeConfigsResourceResult) ConfigSource() int8 {
	return o.configSource
}

func (o *DescribeConfigsResourceResult) SetConfigSource(val int8) {
	o.isNil = false
	o.configSource = val
}

func (o *DescribeConfigsResourceResult) IsSensitive() bool {
	return o.isSensitive
}

func (o *DescribeConfigsResourceResult) SetIsSensitive(val bool) {
	o.isNil = false
	o.isSensitive = val
}

func (o *DescribeConfigsResourceResult) Synonyms() []describeconfigsresourceresult.DescribeConfigsSynonym {
	return o.synonyms
}

func (o *DescribeConfigsResourceResult) SetSynonyms(val []describeconfigsresourceresult.DescribeConfigsSynonym) {
	o.isNil = false
	o.synonyms = val
}

func (o *DescribeConfigsResourceResult) ConfigType() int8 {
	return o.configType
}

func (o *DescribeConfigsResourceResult) SetConfigType(val int8) {
	o.isNil = false
	o.configType = val
}

func (o *DescribeConfigsResourceResult) Documentation() fields.NullableString {
	return o.documentation
}

func (o *DescribeConfigsResourceResult) SetDocumentation(val fields.NullableString) {
	o.isNil = false
	o.documentation = val
}

func (o *DescribeConfigsResourceResult) UnknownTaggedFields() []fields.RawTaggedField {
	return o.unknownTaggedFields
}

func (o *DescribeConfigsResourceResult) SetUnknownTaggedFields(val []fields.RawTaggedField) {
	o.unknownTaggedFields = val
}

func (o *DescribeConfigsResourceResult) Read(buf *bytes.Reader, version int16) error {
	o.SetDefault()

	nameField := fields.String{Context: describeConfigsResourceResultName}
	if err := nameField.Read(buf, version, &o.name); err != nil {
		return errors.WrapIf(err, "couldn't set \"name\" field")
	}

	valueField := fields.String{Context: describeConfigsResourceResultValue}
	if err := valueField.Read(buf, version, &o.value); err != nil {
		return errors.WrapIf(err, "couldn't set \"value\" field")
	}

	readOnlyField := fields.Bool{Context: describeConfigsResourceResultReadOnly}
	if err := readOnlyField.Read(buf, version, &o.readOnly); err != nil {
		return errors.WrapIf(err, "couldn't set \"readOnly\" field")
	}

	isDefaultField := fields.Bool{Context: describeConfigsResourceResultIsDefault}
	if err := isDefaultField.Read(buf, version, &o.isDefault); err != nil {
		return errors.WrapIf(err, "couldn't set \"isDefault\" field")
	}

	configSourceField := fields.Int8{Context: describeConfigsResourceResultConfigSource}
	if err := configSourceField.Read(buf, version, &o.configSource); err != nil {
		return errors.WrapIf(err, "couldn't set \"configSource\" field")
	}

	isSensitiveField := fields.Bool{Context: describeConfigsResourceResultIsSensitive}
	if err := isSensitiveField.Read(buf, version, &o.isSensitive); err != nil {
		return errors.WrapIf(err, "couldn't set \"isSensitive\" field")
	}

	synonymsField := fields.ArrayOfStruct[describeconfigsresourceresult.DescribeConfigsSynonym, *describeconfigsresourceresult.DescribeConfigsSynonym]{Context: describeConfigsResourceResultSynonyms}
	synonyms, err := synonymsField.Read(buf, version)
	if err != nil {
		return errors.WrapIf(err, "couldn't set \"synonyms\" field")
	}
	o.synonyms = synonyms

	configTypeField := fields.Int8{Context: describeConfigsResourceResultConfigType}
	if err := configTypeField.Read(buf, version, &o.configType); err != nil {
		return errors.WrapIf(err, "couldn't set \"configType\" field")
	}

	documentationField := fields.String{Context: describeConfigsResourceResultDocumentation}
	if err := documentationField.Read(buf, version, &o.documentation); err != nil {
		return errors.WrapIf(err, "couldn't set \"documentation\" field")
	}

	// process tagged fields

	if version < DescribeConfigsResourceResultLowestSupportedFlexVersion() || version > DescribeConfigsResourceResultHighestSupportedFlexVersion() {
		// tagged fields are only supported by flexible versions
		o.isNil = false
		return nil
	}

	if buf.Len() == 0 {
		o.isNil = false
		return nil
	}

	rawTaggedFields, err := fields.ReadRawTaggedFields(buf)
	if err != nil {
		return err
	}

	o.unknownTaggedFields = rawTaggedFields

	o.isNil = false
	return nil
}

func (o *DescribeConfigsResourceResult) Write(buf *typesbytes.SliceWriter, version int16) error {
	if o.IsNil() {
		return nil
	}
	if err := o.validateNonIgnorableFields(version); err != nil {
		return err
	}

	nameField := fields.String{Context: describeConfigsResourceResultName}
	if err := nameField.Write(buf, version, o.name); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"name\" field")
	}
	valueField := fields.String{Context: describeConfigsResourceResultValue}
	if err := valueField.Write(buf, version, o.value); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"value\" field")
	}
	readOnlyField := fields.Bool{Context: describeConfigsResourceResultReadOnly}
	if err := readOnlyField.Write(buf, version, o.readOnly); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"readOnly\" field")
	}
	isDefaultField := fields.Bool{Context: describeConfigsResourceResultIsDefault}
	if err := isDefaultField.Write(buf, version, o.isDefault); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"isDefault\" field")
	}
	configSourceField := fields.Int8{Context: describeConfigsResourceResultConfigSource}
	if err := configSourceField.Write(buf, version, o.configSource); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"configSource\" field")
	}
	isSensitiveField := fields.Bool{Context: describeConfigsResourceResultIsSensitive}
	if err := isSensitiveField.Write(buf, version, o.isSensitive); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"isSensitive\" field")
	}

	synonymsField := fields.ArrayOfStruct[describeconfigsresourceresult.DescribeConfigsSynonym, *describeconfigsresourceresult.DescribeConfigsSynonym]{Context: describeConfigsResourceResultSynonyms}
	if err := synonymsField.Write(buf, version, o.synonyms); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"synonyms\" field")
	}

	configTypeField := fields.Int8{Context: describeConfigsResourceResultConfigType}
	if err := configTypeField.Write(buf, version, o.configType); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"configType\" field")
	}
	documentationField := fields.String{Context: describeConfigsResourceResultDocumentation}
	if err := documentationField.Write(buf, version, o.documentation); err != nil {
		return errors.WrapIf(err, "couldn't serialize \"documentation\" field")
	}

	// serialize tagged fields
	numTaggedFields := o.getTaggedFieldsCount(version)
	if version < DescribeConfigsResourceResultLowestSupportedFlexVersion() || version > DescribeConfigsResourceResultHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return nil
	}

	rawTaggedFields := make([]fields.RawTaggedField, 0, numTaggedFields)
	rawTaggedFields = append(rawTaggedFields, o.unknownTaggedFields...)

	if err := fields.WriteRawTaggedFields(buf, rawTaggedFields); err != nil {
		return errors.WrapIf(err, "couldn't serialize tagged fields")
	}

	return nil
}

func (o *DescribeConfigsResourceResult) String() string {
	s, err := o.MarshalJSON()
	if err != nil {
		return err.Error()
	}

	return string(s)
}

func (o *DescribeConfigsResourceResult) MarshalJSON() ([]byte, error) {
	if o == nil || o.IsNil() {
		return []byte("null"), nil
	}

	s := make([][]byte, 0, 10)
	if b, err := fields.MarshalPrimitiveTypeJSON(o.name); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"name\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.value); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"value\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.readOnly); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"readOnly\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.isDefault); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"isDefault\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.configSource); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"configSource\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.isSensitive); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"isSensitive\""), b}, []byte(": ")))
	}
	if b, err := fields.ArrayOfStructMarshalJSON("synonyms", o.synonyms); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.configType); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"configType\""), b}, []byte(": ")))
	}
	if b, err := fields.MarshalPrimitiveTypeJSON(o.documentation); err != nil {
		return nil, err
	} else {
		s = append(s, bytes.Join([][]byte{[]byte("\"documentation\""), b}, []byte(": ")))
	}

	if b, err := fields.ArrayOfStructMarshalJSON("unknownTaggedFields", o.unknownTaggedFields); err != nil {
		return nil, err
	} else {
		s = append(s, b)
	}

	var b bytes.Buffer
	if err := b.WriteByte('{'); err != nil {
		return nil, err
	}
	if _, err := b.Write(bytes.Join(s, []byte(", "))); err != nil {
		return nil, err
	}
	if err := b.WriteByte('}'); err != nil {
		return nil, err
	}

	return b.Bytes(), nil
}

func (o *DescribeConfigsResourceResult) IsNil() bool {
	return o.isNil
}

func (o *DescribeConfigsResourceResult) Clear() {
	o.Release()
	o.isNil = true

	o.synonyms = nil
	o.unknownTaggedFields = nil
}

func (o *DescribeConfigsResourceResult) SetDefault() {
	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil
	o.name.SetValue("")
	o.value.SetValue("")
	o.readOnly = false
	o.isDefault = false
	o.configSource = -1
	o.isSensitive = false
	for i := range o.synonyms {
		o.synonyms[i].Release()
	}
	o.synonyms = nil
	o.configType = 0
	o.documentation.SetValue("")

	o.isNil = false
}

func (o *DescribeConfigsResourceResult) Equal(that *DescribeConfigsResourceResult) bool {
	if !fields.RawTaggedFieldsEqual(o.unknownTaggedFields, that.unknownTaggedFields) {
		return false
	}

	if !o.name.Equal(&that.name) {
		return false
	}
	if !o.value.Equal(&that.value) {
		return false
	}
	if o.readOnly != that.readOnly {
		return false
	}
	if o.isDefault != that.isDefault {
		return false
	}
	if o.configSource != that.configSource {
		return false
	}
	if o.isSensitive != that.isSensitive {
		return false
	}
	if len(o.synonyms) != len(that.synonyms) {
		return false
	}
	for i := range o.synonyms {
		if !o.synonyms[i].Equal(&that.synonyms[i]) {
			return false
		}
	}
	if o.configType != that.configType {
		return false
	}
	if !o.documentation.Equal(&that.documentation) {
		return false
	}

	return true
}

// SizeInBytes returns the size of this data structure in bytes when it's serialized
func (o *DescribeConfigsResourceResult) SizeInBytes(version int16) (int, error) {
	if o.IsNil() {
		return 0, nil
	}

	if err := o.validateNonIgnorableFields(version); err != nil {
		return 0, err
	}

	size := 0
	fieldSize := 0
	var err error

	nameField := fields.String{Context: describeConfigsResourceResultName}
	fieldSize, err = nameField.SizeInBytes(version, o.name)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"name\" field")
	}
	size += fieldSize

	valueField := fields.String{Context: describeConfigsResourceResultValue}
	fieldSize, err = valueField.SizeInBytes(version, o.value)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"value\" field")
	}
	size += fieldSize

	readOnlyField := fields.Bool{Context: describeConfigsResourceResultReadOnly}
	fieldSize, err = readOnlyField.SizeInBytes(version, o.readOnly)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"readOnly\" field")
	}
	size += fieldSize

	isDefaultField := fields.Bool{Context: describeConfigsResourceResultIsDefault}
	fieldSize, err = isDefaultField.SizeInBytes(version, o.isDefault)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"isDefault\" field")
	}
	size += fieldSize

	configSourceField := fields.Int8{Context: describeConfigsResourceResultConfigSource}
	fieldSize, err = configSourceField.SizeInBytes(version, o.configSource)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"configSource\" field")
	}
	size += fieldSize

	isSensitiveField := fields.Bool{Context: describeConfigsResourceResultIsSensitive}
	fieldSize, err = isSensitiveField.SizeInBytes(version, o.isSensitive)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"isSensitive\" field")
	}
	size += fieldSize

	synonymsField := fields.ArrayOfStruct[describeconfigsresourceresult.DescribeConfigsSynonym, *describeconfigsresourceresult.DescribeConfigsSynonym]{Context: describeConfigsResourceResultSynonyms}
	fieldSize, err = synonymsField.SizeInBytes(version, o.synonyms)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"synonyms\" field")
	}
	size += fieldSize

	configTypeField := fields.Int8{Context: describeConfigsResourceResultConfigType}
	fieldSize, err = configTypeField.SizeInBytes(version, o.configType)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"configType\" field")
	}
	size += fieldSize

	documentationField := fields.String{Context: describeConfigsResourceResultDocumentation}
	fieldSize, err = documentationField.SizeInBytes(version, o.documentation)
	if err != nil {
		return 0, errors.WrapIf(err, "couldn't compute size of \"documentation\" field")
	}
	size += fieldSize

	// tagged fields
	numTaggedFields := int64(o.getTaggedFieldsCount(version))
	if numTaggedFields > 0xffffffff {
		return 0, errors.New(strings.Join([]string{"invalid tagged fields count:", strconv.Itoa(int(numTaggedFields))}, " "))
	}
	if version < DescribeConfigsResourceResultLowestSupportedFlexVersion() || version > DescribeConfigsResourceResultHighestSupportedFlexVersion() {
		if numTaggedFields > 0 {
			return 0, errors.New(strings.Join([]string{"tagged fields were set, but version", strconv.Itoa(int(version)), "of this message does not support them"}, " "))
		}

		return size, nil
	}

	taggedFieldsSize := varint.Uint32Size(uint32(numTaggedFields)) // bytes for serializing the number of tagged fields

	for i := range o.unknownTaggedFields {
		length := len(o.unknownTaggedFields[i].Value())
		if int64(length) > 0xffffffff {
			return 0, errors.New(strings.Join([]string{"invalid field value length:", strconv.Itoa(length), ", tag:", strconv.Itoa(int(o.unknownTaggedFields[i].Tag()))}, " "))
		}
		taggedFieldsSize += varint.Uint32Size(o.unknownTaggedFields[i].Tag()) // bytes for serializing the tag of the unknown tag
		taggedFieldsSize += varint.Uint32Size(uint32(length))                 // bytes for serializing the length of the unknown tagged field
		taggedFieldsSize += length
	}

	size += taggedFieldsSize

	return size, nil
}

// Release releases the dynamically allocated fields of this object by returning then to object pools
func (o *DescribeConfigsResourceResult) Release() {
	if o.IsNil() {
		return
	}

	for i := range o.unknownTaggedFields {
		o.unknownTaggedFields[i].Release()
	}
	o.unknownTaggedFields = nil

	o.name.Release()
	o.value.Release()
	for i := range o.synonyms {
		o.synonyms[i].Release()
	}
	o.synonyms = nil
	o.documentation.Release()
}

func (o *DescribeConfigsResourceResult) getTaggedFieldsCount(version int16) int {
	numTaggedFields := len(o.unknownTaggedFields)

	return numTaggedFields
}

// validateNonIgnorableFields throws an error if any non-ignorable field not supported by current version is set to
// non-default value
func (o *DescribeConfigsResourceResult) validateNonIgnorableFields(version int16) error {
	return nil
}

func DescribeConfigsResourceResultLowestSupportedVersion() int16 {
	return 0
}

func DescribeConfigsResourceResultHighestSupportedVersion() int16 {
	return 32767
}

func DescribeConfigsResourceResultLowestSupportedFlexVersion() int16 {
	return 4
}

func DescribeConfigsResourceResultHighestSupportedFlexVersion() int16 {
	return 32767
}

func DescribeConfigsResourceResultDefault() DescribeConfigsResourceResult {
	var d DescribeConfigsResourceResult
	d.SetDefault()

	return d
}
