name: CI

on:
  pull_request:

env:
  GO_VERSION: 1.19
  GOFLAGS: -mod=readonly

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Set Git refname
        id: set-git-refname
        run: echo "git_refname=$(echo "${{ github.ref }}" | sed -r 's@refs/(heads|pull|tags)/@@g')" >> $GITHUB_OUTPUT

      - name: Cache build dependencies
        id: cache-build-dependencies
        uses: actions/cache@v3
        with:
          path: bin/
          key: build-deps-v2-${{ steps.set-git-refname.outputs.git_refname }}-{{ hashFiles('common.mk') }}
          restore-keys: |
            build-deps-v2-${{ steps.set-git-refname.outputs.git_refname }}
            build-deps-v2

      - name: Cache licenses
        id: cache-licenses
        uses: actions/cache@v3
        with:
          path: |
            .licensei.cache
            experimental/heimdall/.licensei.cache
            experimental/mobile/.licensei.cache
          key: licensei-v1-${{ steps.set-git-refname.outputs.git_refname }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            licensei-v1-${{ steps.set-git-refname.outputs.git_refname }}
            licensei-v1

      - name: Download license information for dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Note: this is required for licensei auth in steps to avoid rate-limiting.
        run: make license-cache-all

      - name: List license information for dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Note: this is required for licensei auth in steps to avoid rate-limiting.
        run: ./bin/licensei list

      - name: Check dependency licenses
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Note: this is required for licensei auth in steps to avoid rate-limiting.
        run: make license-check-all

      - name: Run unit tests
        run: make test

      - name: Run lint
        run: make lint-all
