name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO_VERSION: "1.20"
  GOFLAGS: -mod=readonly

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go module dependencies
        id: cache-go-module-dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-mod-cache-${{ runner.os }}-${{ env.GO_VERSION }}
            go-mod-cache-${{ runner.os }}
            go-mod-cache

      - name: Cache build dependencies
        id: cache-build-dependencies
        uses: actions/cache@v3
        with:
          path: bin/
          key: build-deps-v2-{{ hashFiles('common.mk') }}
          restore-keys: |
            build-deps-v2

      - name: Build TCP metadata exchange filter
        run: |
          make tcp-metadata-exchange-filter

      - name: Run unit tests
        run: make test

      - name: Run lint
        run: make lint-all
