name: CI

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Mobile build
    runs-on: macos-12

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup gomobile
        run: |
          git clone --depth 1 -b set-work-dir https://github.com/aeddi/mobile gomobile-cache
          cd gomobile-cache
          go install ./cmd/gomobile
          go install ./cmd/gobind
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true

      - name: Build android framework
        run: |
          cd experimental/mobile
          make android

      - name: Build ios framework
        run: |
          cd experimental/mobile
          make ios
