name: Mobile and Java build

on:
  pull_request:

env:
  GO_VERSION: 1.19
  GOFLAGS: -mod=readonly

jobs:
  build:
    name: Mobile and Java build
    runs-on: macos-12

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Setup gomobile
        run: |
          git clone -b plainjava https://github.com/bonifaido/mobile.git
          cd mobile
          go install ./cmd/gomobile
          go install ./cmd/gobind

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true

      - name: Build plain java library
        working-directory: experimental/java
        run: |
          export JAVA_HOME="$(brew --prefix)/opt/openjdk/"
          make java
          ./mvnw install

      - name: Build spring library
        working-directory: experimental/spring
        run: |
          ./mvnw install

      - name: Build android framework
        working-directory: experimental/mobile
        run: |
          make android

      - name: Build ios framework
        working-directory: experimental/mobile
        run: |
          make ios
