name: CI

on:
  # pull_request:
  push:
    branches:
      - "*"

env:
  GO_VERSION: 1.19
  GOFLAGS: -mod=readonly

jobs:
  build:
    name: Mobile build
    runs-on: macos-12

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Setup gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          go install golang.org/x/mobile/cmd/gobind@latest

      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #     limit-access-to-actor: true

      - name: Build android framework
        run: |
          cd experimental/mobile
          make android

      - name: Build ios framework
        run: |
          cd experimental/mobile
          make ios
